### ISSUE TITLE
Publish to Open VSX Registry

### ISSUE THREAD

**Issue by Zerrissen** [myaaghubi/Andromeda-Mariana-VScode#1]
Can Andromeda Mariana be published to the Open VSX Registry (managed by the Eclipse Foundation), for use with the likes of vscodium and code-server? Insanely underrated theme.

This can be done with the following instructions:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

**Comment by myaaghubi** [comment]
Not soon, but I'll check it as soon as I can.
